name: Deploy to Amazon ECS
description: "Optionally builds and deploys an app to an ECS service"

inputs:
  image-tag:
    description: "Docker image tag to build and/or deploy, defaults to commit sha"
    required: false
    default: ${{ github.sha }}
  ecr-key-id:
    description: "Key id to use at repository"
    required: true
  ecr-access-key:
    description: "Access key to use at repository"
    required: true
  ecr-account-id:
    description: ""
    required: true
  task-definition:
    description: "Task definition family to update"
    required: true
  ecr-name:
    description: ""
    required: true
  service:
    description: ""
    required: true
  cluster:
    description: ""
    required: true


runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3

#    - name: Install AWS CLI v2
#      shell: bash
#      run: |
#        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip
#        unzip -o -q /tmp/awscliv2.zip -d /tmp
#        rm /tmp/awscliv2.zip
#        sudo /tmp/aws/install --update
#        rm -rf /tmp/aws/

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: us-east-2
        role-duration-seconds: 1200
        aws-access-key-id: ${{ inputs.ecr-key-id }}
        aws-secret-access-key: ${{ inputs.ecr-access-key }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registries: ${{ inputs.ecr-account-id }}

    - name: Get current task definition
      id: get-task-def
      shell: bash
      env:
        TASK_FAMILY: ${{ inputs.task-definition }}
      run: |
        aws ecs describe-task-definition --color off --output json --task-definition $TASK_FAMILY --profile carlosmardones-dev |jq .taskDefinition >> current-task-def.json

    - name: Replace image for new deployment
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1.1.3
      with:
        task-definition: current-task-def.json
        container-name: app
        image: "${{ inputs.ecr-account-id }}.dkr.ecr.us-east-2.amazonaws.com/${{ inputs.ecr-name }}:app-${{github.sha}}"

    - name: Deploy new ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1.4.11
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: ${{ inputs.service }}
        cluster: ${{ inputs.cluster }}
        wait-for-service-stability: true